name: afterwards
description: "afterwards app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  get: ^4.7.2
  intl: ^0.20.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  min_sdk_android: 21

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
      - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf

flutter:
  assets:
    - assets/images/
  uses-material-design: true
